### ISSUE TITLE
table editing tool

### ISSUE THREAD

**Issue by robertnowak591** [TUD-INF-IAI-MCI/agsbs_matuc_extension#38]
- improve table editing tool, 
- the user should be able to select the table by clicking it in the markdown document
- close edit csv when changes applied
- choose header in table
- create and edit tables with edit csv

**Comment by kevinunger** [comment]
- [ ] edit tables with edit-csv
- [ ] create tables with edit-csv

**Comment by robertnowak591** [comment]
all new features have been added
